import { Novel, Comic, Author, Genre, Chapter } from '@/types';

// Mock Authors
export const mockAuthors: Author[] = [
    {
        id: '1',
        name: 'Alex Morgan',
        avatar: 'https://i.pravatar.cc/150?img=1',
        followers: 125000,
        isFollowing: false,
        bio: 'Fantasy & Sci-Fi writer | Published author | Coffee enthusiast',
        socialLinks: {
            twitter: 'https://twitter.com',
            instagram: 'https://instagram.com',
        },
    },
    {
        id: '2',
        name: 'Luna Chen',
        avatar: 'https://i.pravatar.cc/150?img=2',
        followers: 98000,
        isFollowing: false,
        bio: 'Webtoon artist | Illustration lover | She/Her',
        socialLinks: {
            twitter: 'https://twitter.com',
            website: 'https://example.com',
        },
    },
    {
        id: '3',
        name: 'James Rivera',
        avatar: 'https://i.pravatar.cc/150?img=3',
        followers: 156000,
        isFollowing: false,
        bio: 'Romance & Drama specialist | 2M+ readers',
        socialLinks: {
            instagram: 'https://instagram.com',
        },
    },
    {
        id: '4',
        name: 'Sophia Lee',
        avatar: 'https://i.pravatar.cc/150?img=4',
        followers: 89000,
        isFollowing: false,
        bio: 'Action & Adventure comics | Fan of anime & manga',
        socialLinks: {
            twitter: 'https://twitter.com',
            instagram: 'https://instagram.com',
        },
    },
    {
        id: '5',
        name: 'Marcus Stone',
        avatar: 'https://i.pravatar.cc/150?img=5',
        followers: 142000,
        isFollowing: false,
        bio: 'Horror & Mystery author | Thriller specialist',
        socialLinks: {
            website: 'https://example.com',
        },
    },
];

// Mock Genres
export const mockGenres: Genre[] = [
    { id: '1', name: 'Fantasy', color: '#8B5CF6' },
    { id: '2', name: 'Romance', color: '#EC4899' },
    { id: '3', name: 'Action', color: '#EF4444' },
    { id: '4', name: 'Comedy', color: '#F59E0B' },
    { id: '5', name: 'Horror', color: '#6B21A8' },
    { id: '6', name: 'Sci-Fi', color: '#0EA5E9' },
    { id: '7', name: 'Drama', color: '#8B5CF6' },
    { id: '8', name: 'Slice of Life', color: '#10B981' },
];

// Mock Chapters
const mockChapters: Chapter[] = [
    {
        id: '1',
        number: 1,
        title: 'The Beginning',
        publishedAt: new Date('2024-01-01'),
        readingTime: 15,
        viewCount: 45000,
        likes: 3200,
    },
    {
        id: '2',
        number: 2,
        title: 'First Encounter',
        publishedAt: new Date('2024-01-08'),
        readingTime: 18,
        viewCount: 42000,
        likes: 3100,
    },
    {
        id: '3',
        number: 3,
        title: 'Hidden Truth',
        publishedAt: new Date('2024-01-15'),
        readingTime: 20,
        viewCount: 38000,
        likes: 2900,
    },
    {
        id: '4',
        number: 4,
        title: 'Revelation',
        publishedAt: new Date('2024-01-22'),
        readingTime: 22,
        viewCount: 35000,
        likes: 2700,
    },
    {
        id: '5',
        number: 5,
        title: 'The Choice',
        publishedAt: new Date('2024-01-29'),
        readingTime: 19,
        viewCount: 32000,
        likes: 2500,
    },
];

// Mock Novels
export const mockNovels: Novel[] = [
    {
        id: 'novel-1',
        title: 'Echoes of the Forgotten Realm',
        description:
            'A young mage discovers an ancient power that could save or destroy their world. Embark on an epic journey through mystical lands filled with wonder and danger.',
        cover: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=400&h=600&fit=crop',
        author: mockAuthors[0],
        genres: [mockGenres[0], mockGenres[6]],
        chapters: mockChapters.map((ch) => ({ ...ch, content: 'Lorem ipsum dolor sit amet...' })),
        status: 'ongoing',
        rating: 4.8,
        views: 2500000,
        likes: 180000,
        follows: 95000,
        createdAt: new Date('2023-06-01'),
        updatedAt: new Date('2024-02-05'),
        isFavorite: false,
        isFollowing: false,
        lastChapterRead: 3,
        readingProgress: 60,
        totalChapters: 157,
    },
    {
        id: 'novel-2',
        title: 'Moonlit Hearts',
        description:
            'A forbidden romance between two souls from rival families. Can love survive ancient feuds? A sweeping tale of passion and sacrifice.',
        cover: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=600&fit=crop',
        author: mockAuthors[2],
        genres: [mockGenres[1], mockGenres[6]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.9,
        views: 3200000,
        likes: 245000,
        follows: 120000,
        createdAt: new Date('2023-03-15'),
        updatedAt: new Date('2024-02-03'),
        isFavorite: true,
        isFollowing: true,
        lastChapterRead: 5,
        readingProgress: 100,
        totalChapters: 89,
    },
    {
        id: 'novel-3',
        title: 'Neon Nexus',
        description:
            'In a cyberpunk future, a hacker discovers a conspiracy that could change everything. Fast-paced sci-fi thriller with stunning world-building.',
        cover: 'https://images.unsplash.com/photo-1536440936694-6af3ee1c5396?w=400&h=600&fit=crop',
        author: mockAuthors[0],
        genres: [mockGenres[5], mockGenres[2]],
        chapters: mockChapters,
        status: 'completed',
        rating: 4.7,
        views: 1800000,
        likes: 150000,
        follows: 65000,
        createdAt: new Date('2023-09-10'),
        updatedAt: new Date('2024-01-20'),
        isFavorite: false,
        isFollowing: false,
        totalChapters: 45,
    },
    {
        id: 'novel-4',
        title: 'Shadows of Yesterday',
        description:
            'A detective must confront her past to solve the present. Dark mystery with plot twists that will keep you guessing until the end.',
        cover: 'https://images.unsplash.com/photo-1507842955343-583cf0270bbb?w=400&h=600&fit=crop',
        author: mockAuthors[4],
        genres: [mockGenres[4], mockGenres[5]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.6,
        views: 1500000,
        likes: 120000,
        follows: 58000,
        createdAt: new Date('2023-11-01'),
        updatedAt: new Date('2024-02-04'),
        isFavorite: false,
        isFollowing: false,
        totalChapters: 78,
    },
    {
        id: 'novel-5',
        title: 'The Last Kingdom',
        description:
            'Epic medieval fantasy with kingdoms at war and heroes rising. Experience a grand tale of conquest, betrayal, and redemption.',
        cover: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=600&fit=crop',
        author: mockAuthors[0],
        genres: [mockGenres[0], mockGenres[2]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.8,
        views: 2900000,
        likes: 215000,
        follows: 105000,
        createdAt: new Date('2023-05-20'),
        updatedAt: new Date('2024-02-02'),
        isFavorite: true,
        isFollowing: false,
        totalChapters: 203,
    },
    {
        id: 'novel-6',
        title: 'Love in Tokyo',
        description:
            'Two strangers meet in the bustling streets of Tokyo. A heartwarming slice-of-life romance set against neon-lit cityscapes.',
        cover: 'https://images.unsplash.com/photo-1519763476592-2c9f22b27e37?w=400&h=600&fit=crop',
        author: mockAuthors[2],
        genres: [mockGenres[1], mockGenres[7]],
        chapters: mockChapters,
        status: 'completed',
        rating: 4.7,
        views: 2100000,
        likes: 185000,
        follows: 89000,
        createdAt: new Date('2023-02-14'),
        updatedAt: new Date('2024-01-15'),
        isFavorite: false,
        isFollowing: false,
        totalChapters: 56,
    },
];

// Mock Comics
export const mockComics: Comic[] = [
    {
        id: 'comic-1',
        title: 'Dragon Chronicles',
        description:
            'An action-packed webtoon about dragon riders and mythical battles. Stunning artwork and intense fight scenes await you.',
        cover: 'https://images.unsplash.com/photo-1616681632179-d3f1e3ce0f1a?w=400&h=600&fit=crop',
        author: mockAuthors[1],
        genres: [mockGenres[0], mockGenres[2]],
        chapters: mockChapters.slice(0, 3),
        status: 'ongoing',
        rating: 4.9,
        views: 4200000,
        likes: 320000,
        follows: 185000,
        createdAt: new Date('2023-04-01'),
        updatedAt: new Date('2024-02-05'),
        isFavorite: true,
        isFollowing: true,
        lastChapterRead: 2,
        readingProgress: 40,
        totalChapters: 89,
    },
    {
        id: 'comic-2',
        title: 'Office Shenanigans',
        description:
            'A hilarious comedy webtoon about office workers and their daily adventures. Perfect for a quick laugh and relatable humor.',
        cover: 'https://images.unsplash.com/photo-1578307584307-40cf7a8ec26a?w=400&h=600&fit=crop',
        author: mockAuthors[3],
        genres: [mockGenres[3], mockGenres[7]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.6,
        views: 1900000,
        likes: 156000,
        follows: 98000,
        createdAt: new Date('2023-07-20'),
        updatedAt: new Date('2024-02-04'),
        isFavorite: false,
        isFollowing: false,
        totalChapters: 112,
    },
    {
        id: 'comic-3',
        title: 'Midnight Guild',
        description:
            'An action-adventure webtoon with magic, mystery, and misadventures. Join a guild of unlikely heroes on their quest for treasure.',
        cover: 'https://images.unsplash.com/photo-1559329007-40790c361539?w=400&h=600&fit=crop',
        author: mockAuthors[1],
        genres: [mockGenres[0], mockGenres[2]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.8,
        views: 3100000,
        likes: 248000,
        follows: 142000,
        createdAt: new Date('2023-08-15'),
        updatedAt: new Date('2024-02-03'),
        isFavorite: false,
        isFollowing: true,
        totalChapters: 156,
    },
    {
        id: 'comic-4',
        title: 'Star Crossed',
        description:
            'A sci-fi romance webtoon set in space. Two pilots from opposing factions find love amidst intergalactic conflict.',
        cover: 'https://images.unsplash.com/photo-1578926314433-6b62cfc69ee7?w=400&h=600&fit=crop',
        author: mockAuthors[3],
        genres: [mockGenres[5], mockGenres[1]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.7,
        views: 2300000,
        likes: 187000,
        follows: 112000,
        createdAt: new Date('2023-10-01'),
        updatedAt: new Date('2024-02-02'),
        isFavorite: true,
        isFollowing: false,
        totalChapters: 78,
    },
    {
        id: 'comic-5',
        title: 'Phantom Echo',
        description:
            'A romance webtoon about college life, friendship, and unexpected love. A cozy read perfect for any time of day.',
        cover: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=600&fit=crop',
        author: mockAuthors[4],
        genres: [mockGenres[4], mockGenres[5]],
        chapters: mockChapters,
        status: 'ongoing',
        rating: 4.5,
        views: 1600000,
        likes: 128000,
        follows: 74000,
        createdAt: new Date('2023-12-01'),
        updatedAt: new Date('2024-02-01'),
        isFavorite: false,
        isFollowing: false,
        totalChapters: 95,
    },
    {
        id: 'comic-6',
        title: 'Sweet Dreams',
        description:
            'A romance webtoon about college life, friendship, and unexpected love. A cozy read perfect for any time of day.',
        cover: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=600&fit=crop',
        author: mockAuthors[1],
        genres: [mockGenres[1], mockGenres[7]],
        chapters: mockChapters,
        status: 'completed',
        rating: 4.8,
        views: 2700000,
        likes: 215000,
        follows: 134000,
        createdAt: new Date('2023-01-10'),
        updatedAt: new Date('2024-01-30'),
        isFavorite: false,
        isFollowing: false,
        totalChapters: 45,
    },
];
